// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaM_jbio4K626U2-poHUgxhMZcQLdMRU',
    appId: '1:499868520702:web:86a076fa66fc6bcadd95af',
    messagingSenderId: '499868520702',
    projectId: 'udal-d56e9',
    authDomain: 'udal-d56e9.firebaseapp.com',
    storageBucket: 'udal-d56e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-taZzM2oTHJmtxL4DlrWvjbcbCgq2ZCQ',
    appId: '1:499868520702:android:e00b47c242b6dcebdd95af',
    messagingSenderId: '499868520702',
    projectId: 'udal-d56e9',
    storageBucket: 'udal-d56e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNFABp3x5iLaMuoCyqaQlkfjRQ8DAwlg',
    appId: '1:499868520702:ios:f00528105ac7b885dd95af',
    messagingSenderId: '499868520702',
    projectId: 'udal-d56e9',
    storageBucket: 'udal-d56e9.firebasestorage.app',
    androidClientId: '499868520702-o5l3qvlflfp2voutnjl6q5sqcj143sap.apps.googleusercontent.com',
    iosClientId: '499868520702-iud3cml47n039pbv7vtiek6enfeqn8ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleankudla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNFABp3x5iLaMuoCyqaQlkfjRQ8DAwlg',
    appId: '1:499868520702:ios:f00528105ac7b885dd95af',
    messagingSenderId: '499868520702',
    projectId: 'udal-d56e9',
    storageBucket: 'udal-d56e9.firebasestorage.app',
    androidClientId: '499868520702-o5l3qvlflfp2voutnjl6q5sqcj143sap.apps.googleusercontent.com',
    iosClientId: '499868520702-iud3cml47n039pbv7vtiek6enfeqn8ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleankudla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaM_jbio4K626U2-poHUgxhMZcQLdMRU',
    appId: '1:499868520702:web:a40ed27b9289e93add95af',
    messagingSenderId: '499868520702',
    projectId: 'udal-d56e9',
    authDomain: 'udal-d56e9.firebaseapp.com',
    storageBucket: 'udal-d56e9.firebasestorage.app',
  );
}
